name: Build and deploy ASP.Net Core app to Azure Web App - BeautyContestVotingSystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Remove Artifact
        # You may pin to the exact commit or the version.
        # uses: remagpie/gha-remove-artifact@17a089caac8f6b2bbcb3a2dab795ec6228e7d6e2
        uses: remagpie/gha-remove-artifact@v1
        with:
          # Access token for the repository.
          GITHUB_TOKEN: ${{ github.token }} # default is ${{ github.token }}
          # Exact string for filtering artifacts by name.
          # only-name: # optional
          # Regex for filtering artifacts by name.
          # regex-name: # optional
          # Maximum number of artifacts to keep.
          # max-count: # optional
          # Maximum age(by seconds) of artifacts to keep.
          # max-age: # optional
        
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BeautyContestVotingSystem'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F615F0D4F4364CFB8E3B01842C317270 }}
          package: .
